#!/usr/bin/env python3
"""Build website/assets/data/search-index.js from the HTML pages.
Idempotent. URLs relative to website/ root. Run: python3 website/tools/build-index.py"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "data", "search-index.js")

SECTION_FOR = {
    "docs/": "Docs",
}
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")


def text_of(path):
    with open(path, encoding="utf-8") as f:
        raw = f.read()
    m = re.search(r"<main[^>]*>(.*?)</main>", raw, re.S)
    body = m.group(1) if m else raw
    title = re.search(r"<title>(.*?)</title>", raw, re.S)
    t = html.unescape(TAG_RE.sub("", title.group(1))).strip() if title else os.path.basename(path)
    h1 = re.search(r"<h1[^>]*>(.*?)</h1>", body, re.S)
    if h1:
        t = html.unescape(TAG_RE.sub("", h1.group(1))).strip() or t
    txt = html.unescape(TAG_RE.sub(" ", body))
    return t, WS_RE.sub(" ", txt).strip()[:1200]


def main():
    entries = []
    for dirpath, _dirs, files in os.walk(ROOT):
        for fn in sorted(files):
            if not fn.endswith(".html"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
            if rel.startswith("fr/"):
                section = "FR"
            elif rel.startswith("docs/"):
                section = "Docs"
            else:
                section = "Site"
            title, text = text_of(full)
            entries.append({"t": title, "s": section, "u": rel, "x": text})
    entries.sort(key=lambda e: e["u"])
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* generated by website/tools/build-index.py — do not hand-edit */\n")
        f.write("window.AR_SEARCH = ")
        json.dump(entries, f, ensure_ascii=False)
        f.write(";\n")
    print("index: %d pages -> %s" % (len(entries), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
