# Variante classic-nopanel — générée, ne pas éditer à la main.
# configs/kde/plasma-org.kde.plasma.desktop-appletsrc
# Layout ArchRicing : 1 panneau supérieur fin translucide + 1 dock bas-centre flottant.
# AUCUN widget invasif. Le dock est un panneau Plasma natif (pas latte-dock).
[Containments][2]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][2][General]
lengthMode=1
alignment=132
offset=0
thickness=48
floating=false
opacity=65

[Containments][2][Applets][10]
plugin=org.kde.plasma.kickoff
[Containments][2][Applets][11]
plugin=org.kde.plasma.icon
[Containments][2][Applets][12]
plugin=org.kde.plasma.icontasks
