--- # calamares/modules/services-systemd.conf — services activés sur le système installé
services:
  - name: "sddm"
    mandated: true
  - name: "NetworkManager"
    mandated: true
  - name: "bluetooth"
    mandated: false
targets:
  - name: "graphical"
    mandated: true
