--- # module shellprocess post-install ArchRicing (instance @archricing-postinstall)
# IMPORTANT : le nom de ce fichier doit être shellprocess@archricing-postinstall.conf
# pour correspondre à l'entrée "shellprocess@archricing-postinstall" de settings.conf.
dontChroot: false
timeout: 600
script:
  - command: "/usr/local/bin/archricing-postinstall"
