--- # calamares/modules/unpackfs.conf — décompresse l'image live vers la cible
unpack:
  - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
    exclude:
      - "/sys/**"
      - "/dev/**"
      - "/proc/**"
      - "/run/**"
      - "/tmp/**"
