--- # calamares/settings/settings.conf
prompt-install: false
dont-chroot: false
oem-mode: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - packagechooser@edition
      - archricing_experience
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader-config
      - bootloader
      - packagechooser
      - packages
      - archricing_experience
      - shellprocess@archricing-postinstall
      - umount
  - show:
      - finished
branding: archricing
promo: welcome
